version: '3.7'
services:
    db:
        image: postgres:10.1-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        environment:
            - SECRET_KEY=just_for_training_purposes
            - DEBUG=True
            - HEROKU_URL=url
        depends_on:
            - db
    chrome:
        image: selenium/standalone-chrome-debug:3.141.59-yttrium
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
       # network_mode: "host"
volumes:
    postgres_data:
